version: '3.8'

services:
  # Your Node.js application
  app:
    build: .
    ports:
      - "3010:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:pass123!@db:5432/postgres
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    restart: unless-stopped

  # PostgreSQL database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass123!
      - POSTGRES_DB=postgres
    ports:
      - "5499:5432"  # Map host port 5499 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: